[package]
name = "lane_merging_simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8.0"
bevy_physimple = "0.5.0"
pid = "3.0.0"
serde = "1.0.149"
